- name: 安装单节点mariadb
  yum: name={{ item }} state=present
  with_items:
   - mariadb
   - mariadb-server

- name: copying config files
  template: src=templates/mariadb-server.cnf.j2 dest=/etc/my.cnf.d/mariadb-server.cnf owner=root group=root mode=0644

- name : start mariadb
  service : name=mariadb state=restarted enabled=true

