---
- name: copy zabbix.repo
  template: src=templates/zabbix.repo.j2 dest=/etc/yum.repos.d/zabbix.repo owner=root group=root mode=0644

- name: copy epel.repo
  template: src=templates/epel-7.repo.j2 dest=/etc/yum.repos.d/epel-7.repo owner=root group=root mode=0644


- name: install python-pip python-devel mysql-devel
  yum: name={{ item }} state=present
  with_items:
   - python-pip
   - python-devel
   - mysql-devel

- name: 安装zabbix-server
  yum: name={{ item }} state=present
  with_items:
   - zabbix-server-mysql-3.4.1
   - zabbix-web-mysql-3.4.1
   - zabbix-agent-3.4.1
   - MySQL-python

#- name: 升级pip
#  command: pip install --upgrade pip

#- name: Install the Python MySQLB module
#  yum: name=MySQL-python state=present
#  pip: name=MySQL-python state=forcereinstall


- name: 创建数据库
  mysql_db: 
    name: zabbix
    encoding: utf8
    state: present

#- name: 授权
#  mysql_user:
#    name: {{ mysql_user_name }}
#    password: {{ mysql_user_password }}
#    priv: 'zabbix.*:ALL,GRANT'
#    state: present

- name: set permission on mysql_user_name
  mysql_user: name={{ mysql_user_name }} password={{ mysql_user_password }} priv='*.*:ALL,GRANT' state=present host={{ item }}
  with_items:
   - "%"
   - "localhost"
   - "{{ ansible_default_ipv4.address }}"
#   - "hostvars[inventory_hostname]['ansible_default_ipv4']['address']"
  tags:
    - auth


- name: 解压数据库文件
  command: gzip -dr create.sql.gz
  args:
    chdir: /usr/share/doc/zabbix-server-mysql-3.4.1
  ignore_errors: yes

- name: 导入数据结构
  mysql_db:
    state: import
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql-3.4.1/create.sql

- name: copy zabbix-server配置文件
  template: src=templates/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=0644

- name: copy zabbix-agentd配置文件
  template: src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644


- name: copy zabbix.conf配置文件
  template: src=templates/zabbix.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf owner=root group=root mode=0644


- name: copy php.ini
  template: src=templates/php.ini.j2 dest=/etc/php.ini owner=root group=root mode=0644

- name: set permission on zabbix_server.conf
  shell: chown apache:apache /etc/zabbix/zabbix_server.conf


- name: start server and agent
  service: name={{ item }} state=restarted enabled=True
  with_items:
   - zabbix-server
   - zabbix-agent

- name: setenforce 0
  command: setenforce 0

- name: resart httpd service
  service: name=httpd state=restarted enabled=yes

