---
- name: 配置源
  yum: name={{ item }} state=present
  with_items:
   - http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm 
   - python-pip
   - python-devel
   - mysql-devel

- name: 安装zabbix-server
  yum: name={{ item }} state=present
  with_items:
   - zabbix-server-mysql
   - zabbix-web-mysql
   - zabbix-agent

- name: 升级pip
  command: pip install --upgrade pip

- name: Install the Python MySQLB module
  pip: name=MySQL-python state=forcereinstall


- name: 创建数据库
  mysql_db: 
    name: zabbix
    encoding: utf8
    state: present

- name: 授权
  mysql_user:
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL,GRANT'
    state: present

- name: 解压数据库文件
  command: gzip create.sql.gz
  args:
    chdir: /usr/share/doc/zabbix-server-mysql-3.4.1

- name: 导入数据结构
  mysql_db:
    state: import
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql-3.4.1/create.sql

- name: copy zabbix-server配置文件
  template: src=templates/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=0644

- name: copy zabbix-agentd配置文件
  template: src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644


- name: copy zabbix.conf配置文件
  template: src=templates/zabbix.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf owner=root group=root mode=0644


- name: copy php.ini
  template: src=templates/php.ini.j2 dest=/etc/php.ini owner=root group=root mode=0644

- name: start server and agent
  service: name={{ item }} state=restarted enabled=True
  with_items:
   - zabbix-server
   - zabbix-agent


- name: resart httpd service
  service: name=httpd state=restarted enabled=yes

